### ISSUE TITLE
IDF() - IOError "No such file or directory"

### ISSUE THREAD

**Issue by grilloz89** [santoshphilip/eppy#145]
The error is relative to the .idd file which can't be found.

I keep getting this error while calling the IDF() function on the sample .idf file  (I am simply going through the tutorial, same exact steps).
At first I thought of some syntax error on the paths provided to the functions but that does not seem to be the case, I have also tried to give  absolute paths just to be sure.

I am using Anaconda (32bit) with python 2.7. Thanks!!

**Comment by jamiebull1** [comment]
Can you provide the traceback?

**Comment by santoshphilip** [comment]
Can you post a printout of the error message and the code that leads to it

**Comment by grilloz89** [comment]
`idf1 = IDF(fname1)
Traceback (most recent call last):

  File "<ipython-input-72-22664b307544>", line 1, in <module>
    idf1 = IDF(fname1)

  File "C:\Users\Andrea\Anaconda2\lib\site-packages\eppy\modeleditor.py", line 543, in __init__
    self.read()

  File "C:\Users\Andrea\Anaconda2\lib\site-packages\eppy\modeleditor.py", line 663, in read
    commdct=self.idd_info, block=self.block)

  File "C:\Users\Andrea\Anaconda2\lib\site-packages\eppy\idfreader.py", line 204, in idfreader1
    versiontuple = iddversiontuple(iddfile)

  File "C:\Users\Andrea\Anaconda2\lib\site-packages\eppy\idfreader.py", line 30, in iddversiontuple
    fhandle = open(afile, 'rb')

IOError: [Errno 2] No such file or directory: '../eppy/resources/iddfiles/Energy+V7_2_0.idd'`

**Comment by santoshphilip** [comment]
what directory are you running the script from ?

**Comment by grilloz89** [comment]
```
idf1 = IDF(fname1)
Traceback (most recent call last):

  File "<ipython-input-72-22664b307544>", line 1, in <module>
    idf1 = IDF(fname1)

  File "C:\Users\Andrea\Anaconda2\lib\site-packages\eppy\modeleditor.py", line 543, in __init__
    self.read()

  File "C:\Users\Andrea\Anaconda2\lib\site-packages\eppy\modeleditor.py", line 663, in read
    commdct=self.idd_info, block=self.block)

  File "C:\Users\Andrea\Anaconda2\lib\site-packages\eppy\idfreader.py", line 204, in idfreader1
    versiontuple = iddversiontuple(iddfile)

  File "C:\Users\Andrea\Anaconda2\lib\site-packages\eppy\idfreader.py", line 30, in iddversiontuple
    fhandle = open(afile, 'rb')

IOError: [Errno 2] No such file or directory: '../eppy/resources/iddfiles/Energy+V7_2_0.idd'
```

I am working from a new empy folder on my desktop

**Comment by santoshphilip** [comment]
the code you are running is designed to run from `./eppy/doc` folder. If you are running it from a different folder, you can give the full path name to the `idd` in your installed Energyplus (eppy will run with any version)

You code may look like this:

    iddfile = "c:/EnergyplusV-8/Energy.idd" # make sure this is right. I am on a Mac and don't have the right pathname

    IDF.setiddname(iddfile)
    idf1 = IDF(fname1)

**Comment by grilloz89** [comment]
this way I get the following error.

```
iddfile = "‪C:\EnergyPlusV8-6-0\Energy+.idd"

IDF.setiddname(iddfile)
Traceback (most recent call last):

  File "<ipython-input-78-030c777d3e17>", line 1, in <module>
    IDF.setiddname(iddfile)

  File "C:\Users\Andrea\Anaconda2\lib\site-packages\eppy\modeleditor.py", line 575, in setiddname
    raise IDDAlreadySetError(errortxt)

IDDAlreadySetError: IDD file is set to: ../eppy/resources/iddfiles/Energy+V7_2_0.idd
```

the path in the error returned from this code is the one I had previously set; which is also the same where python couldn't find the file (in the previously posted code).

**Comment by santoshphilip** [comment]
Eppy allows you to set the IDD file only once.
Once it is set, you cannot change it.

run the script again (if you are on command line)
I am unfamiliar with Anaconda. I assume, you can restart the script

**Comment by santoshphilip** [comment]
Hope this is working.
I am signing off for now - will not be online for some time

**Comment by grilloz89** [comment]
Restarting Anaconda I was able to reset the path to the .idd file. Everything works fine now. Thanks!!
