### ISSUE TITLE
unknown field U-Factor for WindowMaterial:SimpleGlazingSystem

### ISSUE THREAD

**Issue by katsuya0719** [santoshphilip/eppy#198]
I am having error when I try to extract information from `U-Factor` attribute as below.  I tried "U_Factor", but also got same error. Does anyone know how I can specify `U-Factor`?

> Traceback (most recent call last):
  File "C:/Users/obakatsu/Documents/Python_scripts/EnergyPlus/PostprocessEP/EPengine/parseidf.py", line 90, in <module>
    json = parsed.readidf(objdict)
  File "C:/Users/obakatsu/Documents/Python_scripts/EnergyPlus/PostprocessEP/EPengine/parseidf.py", line 28, in readidf
    attrList=self.readattrs(i,attrs[i])
  File "C:/Users/obakatsu/Documents/Python_scripts/EnergyPlus/PostprocessEP/EPengine/parseidf.py", line 55, in readattrs
    attrList.append(obj[attr])
  File "C:\Users\obakatsu\Anaconda3\lib\site-packages\eppy\bunch_subclass.py", line 325, in __getitem__
    raise BadEPFieldError(astr)
eppy.bunch_subclass.BadEPFieldError: unknown field U-Factor

**Comment by santoshphilip** [comment]
try `UFactor`

You can get all the filenames by `simplglazing.fieldnames` where `simpleglazing` is the `WindowMaterial:SimpleGlazingSystem`idfobject

**Comment by santoshphilip** [comment]
@katsuya0719 , any luck with `UFactor`.
Let me know if it is working or not working.

I'll close the issue if it is working.

**Comment by katsuya0719** [comment]
Sorry for late reply. It worked! Thank you!  
Can I assume that any attribute with "-" can be ignored to specify using eppy API?

**Comment by santoshphilip** [comment]
"-" cannot be used because it is a symbol for subtraction. I'll make an update to the documentation to make this clear
