### ISSUE TITLE
File not found on executing idf.run()

### ISSUE THREAD

**Issue by MR1107** [santoshphilip/eppy#270]
Hello,

I am new to Python and eppy. I wrote the following simple code;

from eppy import modeleditor
from eppy.modeleditor import IDF
iddfile = r"Energy+.idd"
fname1= r"ASHRAE90.1_OfficeSmall_STD2004_PortAngeles.idf"
epwfile = r"Atlanta.epw"
idf = IDF.setiddname(iddfile)
idf = IDF(fname1,epwfile)
idf.run()

The program is throwing following exception;

Traceback (most recent call last):
  File "1.py", line 15, in <module>
    idf.run()
  File "C:\Python37\lib\site-packages\eppy\modeleditor.py", line 1014, in run
    run(self, weather=epw, idd=idd, **kwargs)
  File "C:\Python37\lib\site-packages\eppy\runner\run_functions.py", line 357, in run
    check_call(cmd)
  File "C:\Python37\lib\subprocess.py", line 342, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Python37\lib\subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

I have run other idf functions (idf.printidf()) and they seem to be working fine. Please help!

MR

**Comment by santoshphilip** [comment]
which version of eppy is this ?

**Comment by MR1107** [comment]
Hey Santosh,

Thank you for replying. I figured with the help of a colleague that the version of idd file that I was using was different from one that was installed on my computer.

The code worked fine after that.

Best Regards,
Mayuri
