### ISSUE TITLE
 failed drawing of loopdiagram

### ISSUE THREAD

**Issue by missermann** [santoshphilip/eppy#272]
I wanted to draw a loopdiagram with the in eppy provided script but it
failed with the following message:

 Couldn't import dot_parser, loading of dot files will not be possible.
constructing the loops
Traceback (most recent call last):
  File "loopdiagram.py", line 572, in <module>
    sys.exit(main())
  File "loopdiagram.py", line 568, in main
    make_and_save_diagram(args.file, args.idd)
  File "loopdiagram.py", line 524, in make_and_save_diagram
    g = process_idf(fname, iddfile)
  File "loopdiagram.py", line 531, in process_idf
    edges = makeairplantloop(data, commdct)
  File "loopdiagram.py", line 364, in makeairplantloop
    equipconnections = loops.extractfields(data, commdct, objkey,
fieldlists)
  File
"/home/maikel/Software/anaconda3/envs/wupper/lib/python3.6/site-packages/eppy/loops.py",
line 46, in extractfields
    fieldindex.append(objfields.index(item) + 0)
ValueError: 'Zone Return Air Node Name' is not in list

I attached the concerned idf. It has a Zone Return Air Node Name.
Do you have any idea how to fix the error?

[294621715.txt](https://github.com/santoshphilip/eppy/files/4254641/294621715.txt)

**Comment by santoshphilip** [comment]
loop diagram works upto version 8.5 (I had used it for a version 8.5 successfully)
Something may have changed in the way E+ builds/defines loops
I think the code will need to be updated for version 8.9

Loop diagram is a bit of a hack. (written because of desperate need)
I won't be able to get to it for a few days.

If you are comfortable with python, you may want to take a look at the code. There is a chance it maybe an easy fix. (I can merge your fix into the main branch)

**Comment by borlum** [comment]
@missermann did you ever look into a fix? I have just stumbled on this, and could see the benefit of this working on E+ version > 8.5.

**Comment by santoshphilip** [comment]
I have not gotten to it yet.
If you are familiar with how loops are built, can you take a look (compare 8.5 example with one later)
there is a chance that the fix is simple

**Comment by borlum** [comment]
No worries - if I find the time, I will take a look at it. Kudos on eppy. Super helpful for querying E+ models and manipulating them from Python.
