### ISSUE TITLE
Running idf.run() causes a CalledProcessError and EnergyPlusRunError

### ISSUE THREAD

**Issue by anjukan** [santoshphilip/eppy#306]
Hi @santoshphilip and @jamiebull1 ,

Hope you are well. I'd just like to report an issue I am having with idf.run() causing an E+ CalledProcessError and EnergyPlusRunError. I am using eppy v0.5.52, python 3.7.6 and EnergyPlus v8.5.0.

My test code is as follows:
```
import sys

pathnameto_eppy = 'C:/ProgramData/Anaconda3/envs/tf/lib/site-packages/eppy'
sys.path.append(pathnameto_eppy)

#import eppy
from eppy import modeleditor
from eppy.modeleditor import IDF

try:
	IDF.setiddname('Energy+.idd')
except modeleditor.IDDAlreadySetError as e:
	pass

idfname = r"pyEp/Ref/1ZoneEvapCooler.idf"
epwname = 'C:/EnergyPlusV8-5-0\WeatherData/ITA_Rome.162420_IWEC.epw'

idf = IDF(idfname, epw = epwname)

idf.run(expandobjects = True, verbose="v", output_directory = r"pyEp/Ref/", readvars = True, output_suffix = 'C')
```

Running this code gives the following error message:
```
C:/EnergyPlusV8-5-0\energyplus.exe --weather C:\EnergyPlusV8-5-0\WeatherData\ITA_Rome.162420_IWEC.epw --output-directory C:\Users\AnjukanK\Documents\Anjukan\Anaconda Projects\PyEp_gym\pyEp\Ref --idd Energy+.idd --expandobjects --readvars --output-suffix C C:\Users\AnjukanK\Documents\Anjukan\Anaconda Projects\PyEp_gym\in.idf

Traceback (most recent call last):

  File "C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\eppy\runner\run_functions.py", line 357, in run
    check_call(cmd)

  File "C:\ProgramData\Anaconda3\envs\tf\lib\subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)

CalledProcessError: Command '['C:/EnergyPlusV8-5-0\\energyplus.exe', '--weather', 'C:\\EnergyPlusV8-5-0\\WeatherData\\ITA_Rome.162420_IWEC.epw', '--output-directory', 'C:\\Users\\AnjukanK\\Documents\\Anjukan\\Anaconda Projects\\PyEp_gym\\pyEp\\Ref', '--idd', 'Energy+.idd', '--expandobjects', '--readvars', '--output-suffix', 'C', 'C:\\Users\\AnjukanK\\Documents\\Anjukan\\Anaconda Projects\\PyEp_gym\\in.idf']' returned non-zero exit status 1.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\AnjukanK\Documents\Anjukan\Anaconda Projects\PyEp_gym\eppy_test.py", line 31, in <module>
    idf.run(expandobjects = True, verbose="v", output_directory = r"pyEp/Ref/", readvars = True, output_suffix = 'C')

  File "C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\eppy\modeleditor.py", line 1014, in run
    run(self, weather=epw, idd=idd, **kwargs)

  File "C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\eppy\runner\run_functions.py", line 362, in run
    raise EnergyPlusRunError(message)

EnergyPlusRunError: 

Contents of EnergyPlus error file at C:\Users\AnjukanK\Documents\Anjukan\Anaconda Projects\PyEp_gym\pyEp\Ref\eplusout.err
<File not found>
```

The idf runs fine when using both EP Launch and the command line. I have checked that all files are in their stated locations. I have tried different IDF files with the same error. I have gotten idf.run() to work in another python installation with eppy v0.5.46 and python 3.4.3 so not sure if that is the issue? Any idea what I could be doing wrong?

**Comment by santoshphilip** [comment]
ack your message.
Your code looks good at first glance.

I'll test later today and see what comes up

**Comment by santoshphilip** [comment]
sorry it took so long to get to this. I am on it now.

**Comment by santoshphilip** [comment]
OK. I think I found the problem. It may be in your code. I tested the following code and it worked.

    """resolving issue #306"""
    # import sys
    #
    # pathnameto_eppy = 'C:/ProgramData/Anaconda3/envs/tf/lib/site-packages/eppy'
    # sys.path.append(pathnameto_eppy)

    import eppy
    from eppy import modeleditor
    from eppy.modeleditor import IDF

    try:
    	IDF.setiddname('/Applications/EnergyPlus-8-5-0/Energy+.idd')
    except modeleditor.IDDAlreadySetError as e:
    	pass

    idfname = "/Applications/EnergyPlus-8-5-0/ExampleFiles/1ZoneEvapCooler.idf"
    epwname = '/Applications/EnergyPlus-8-5-0/WeatherData/USA_CA_San.Francisco.Intl.AP.724940_TMY3.epw'

    idf = IDF(idfname, epw = epwname)

    idf.run(expandobjects = True, verbose="v", output_directory = "./out_folder", readvars = True, output_suffix = 'C')

See further comment below

**Comment by santoshphilip** [comment]
I think that in your code

`output_directory = r"pyEp/Ref/"`

this directory does not exist
Your code may work if you make this directory

**Comment by anjukan** [comment]
Hi @santoshphilip , thank you for getting back to me. I just had a chance to try this and unfortunately this does not resolve the issue. I still get the same error trying a new folder called "out_folder" as your example above or even removing this key variable completely on the idf.run() call.

**Comment by santoshphilip** [comment]
@anjukan 
Can you run the following code and tell me what result you get::

    import os
    ptho = "C:/Users/AnjukanK/Documents/Anjukan/Anaconda Projects/PyEp_gym/pyEp/Ref"
    result = os.path.exists(ptho)
    print(f'result = {result}')

**Comment by anjukan** [comment]
Hi @santoshphilip, I just tried that, I get the following:

result = True

**Comment by santoshphilip** [comment]
I want to test out a different suspicion. 
(You may see what I am trying to do here)

Case1: run this from command line

    C:/EnergyPlusV8-5-0\energyplus.exe --weather C:\EnergyPlusV8-5-0\WeatherData\ITA_Rome.162420_IWEC.epw --output-directory C:\Users\AnjukanK\Documents\Anjukan\Anaconda Projects\PyEp_gym\pyEp\Ref --idd Energy+.idd --expandobjects --readvars --output-suffix C C:\Users\AnjukanK\Documents\Anjukan\Anaconda Projects\PyEp_gym\in.idf


Case2: run this from command line

    C:\EnergyPlusV8-5-0\energyplus.exe --weather C:\EnergyPlusV8-5-0\WeatherData\ITA_Rome.162420_IWEC.epw --output-directory "C:\Users\AnjukanK\Documents\Anjukan\Anaconda Projects\PyEp_gym\pyEp\Ref" --idd Energy+.idd --expandobjects --readvars --output-suffix C "C:\Users\AnjukanK\Documents\Anjukan\Anaconda Projects\PyEp_gym\in.idf"


Tell me what happens in each case. Give me the error messages in Case1 and Case2

**Comment by santoshphilip** [comment]
What I asked you to do in the previous comment is not going to be useful in debugging :-(
So don't do it

**Comment by santoshphilip** [comment]
I may have to get on a Windows machine and test with conditions close to your machine.
You are using Anaconda that I am very unfamiliar with.
Let me see it I can recreate the problem without Anaconda first.

**Comment by anjukan** [comment]
Sure @santoshphilip , appreciate it. I'll be responsive anyway if you require anything further from me.

**Comment by santoshphilip** [comment]
I am not able to get access to a Windows machine. Not able to recreate this error.
(Works fine on my end on Unix/mac)

Can anyone test it our and recreate this problem ?
@lafrech , @jamiebull1 , @samuelduchesne, @daren-thomas,  @jasonglazer

**Comment by santoshphilip** [comment]
I just noticed this in the documentation from @jamiebull1 

It says:

Note 1: idf.run() works for E+ version >= 8.3 Note 2: idf.run(readvars=True) has been tested only for E+ version >= 8.9. It may work with earlier versions

@anjukan This is a long shot. Can you try running without readvars=True
I don't think it should make a difference. But it is worth a shot.

**Comment by anjukan** [comment]
Hi @santoshphilip , I can confirm that removing readvars = True and running makes no difference to the error.

**Comment by santoshphilip** [comment]
thanks.Not having access to a Windows machine in no helping me here :-(. 
Let's blame the lockdown for that.
    On Monday, October 26, 2020, 03:11:03 AM PDT, Anjukan Kathirgamanathan <notifications@github.com> wrote:  
 
 


Hi @santoshphilip , I can confirm that removing readvars = True and running makes no difference to the error.

**Comment by santoshphilip** [comment]
another long shot.

can you remove all the backslashes in your code and make them from slashes

    epwname = 'C:/EnergyPlusV8-5-0\WeatherData/ITA_Rome.162420_IWEC.epw'
    # becomes
    epwname = 'C:/EnergyPlusV8-5-0/WeatherData/ITA_Rome.162420_IWEC.epw'

Tell me what happens

**Comment by anjukan** [comment]
No luck with that either sorry :/

**Comment by santoshphilip** [comment]
I made some additions to the documentation. Can you look at these three links and try out the code. Let me know how it works out (or does not work). Modify the code as needed.

- [Running in parallel processes](https://eppy.readthedocs.io/en/latest/runningeplus.html#Running-in-parallel-processes)
- [Running in parallel processes using Generators](https://eppy.readthedocs.io/en/latest/runningeplus.html#Running-in-parallel-processes-using-Generators)
- [Make idf.run() work like EPLaunch](https://eppy.readthedocs.io/en/latest/runningeplus.html#Make-idf.run()-work-like-EPLaunch)

Safari browser is not showing some pages. May not be an issue for you

**Comment by anjukan** [comment]
Hi @santoshphilip, thanks for that. I tried both the idf.run() on its own and through the 'make_eplaunch_options' function. I get the same errors as reported in the original post with both options.

I upgraded eppy to v0.5.53 and tried both the example 1ZoneEvapCooler and my own idf.

**Comment by santoshphilip** [comment]
:-(

**Comment by santoshphilip** [comment]
@anjukan , I ran into the same error in my work.
I tracked it down to version number of the `idd` not matching the version number in the `idf`

Can you test with the full path name in this way:

    IDF.setiddname('C:/EnergyPlusV8-5-0/Energy+.idd')

Now your full script would look like this:

    import sys

    pathnameto_eppy = 'C:/ProgramData/Anaconda3/envs/tf/lib/site-packages/eppy'
    sys.path.append(pathnameto_eppy)

    #import eppy
    from eppy import modeleditor
    from eppy.modeleditor import IDF

    try:
    	IDF.setiddname('C:/EnergyPlusV8-5-0/Energy+.idd')
    except modeleditor.IDDAlreadySetError as e:
    	pass

    idfname = r"pyEp/Ref/1ZoneEvapCooler.idf"
    epwname = 'C:/EnergyPlusV8-5-0/WeatherData/ITA_Rome.162420_IWEC.epw'

    idf = IDF(idfname, epw = epwname)

    idf.run(expandobjects = True, verbose="v", output_directory = r"pyEp/Ref/", readvars = True, output_suffix = 'C')

Also confirm that the version number in the `idf` is `8.5`
