### ISSUE TITLE
Troubles in running Eppy from Grasshopper

### ISSUE THREAD

**Issue by fracarl** [santoshphilip/eppy#311]
Good morning,
I wrote a code to run energy analysis from Python 3.8 in Spyder (Anaconda3) and it works. In a few words, my code modifies the idf file and then launches the analysis in EnergyPlus. I was trying to use this code in grasshopper using GH_CPython code (with this path C:\Users\Pc\anaconda3\python.exe) but I'm facing different problems, it would be great to have help from you.

I have created a rhinoremote environment and imported all the scripts needed for my Python code (Eppy which is installed in anaconda) and the code seems to work if I modify my .idf file or save it. But if I try to launch the analysis it doesn't work and it gives me the attached error.

C:\Users\Pc\anaconda3\lib\site-packages\numpy_init_.py:140: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
from . import _distributor_init
Traceback (most recent call last):
File "C:\GH_CPython\PythonFileWritten_1.py", line 27, in
idf.run(readvars=True, expandobjects=True,output_directory=os.path.join(folderpath,"Output"))
File "C:\Users\Pc\anaconda3\lib\site-packages\eppy\modeleditor.py", line 1009, in run
self.saveas("in.idf")
File "C:\Users\Pc\anaconda3\lib\site-packages\eppy\modeleditor.py", line 974, in saveas
self.save(filename, lineendings, encoding)
File "C:\Users\Pc\anaconda3\lib\site-packages\eppy\modeleditor.py", line 947, in save
with open(filename, "wb") as idf_out:
PermissionError: [Errno 13] Permission denied: 'in.idf'

Any suggestions?

**Comment by fracarl** [comment]
I have solved the error due to numpy (changing the python path with C:\Users\Pc\anaconda3\envs\rhinoremote\python.exe) and now the the traceback is the following:

Traceback (most recent call last):
File "C:\GH_CPython\PythonFileWritten_1.py", line 28, in
idf.run(readvars=True, expandobjects=True,output_directory=os.path.join(folderpath,"Output"))
File "C:\Users\Pc\anaconda3\envs\rhinoremote\lib\site-packages\eppy\modeleditor.py", line 1009, in run
self.saveas("in.idf")
File "C:\Users\Pc\anaconda3\envs\rhinoremote\lib\site-packages\eppy\modeleditor.py", line 974, in saveas
self.save(filename, lineendings, encoding)
File "C:\Users\Pc\anaconda3\envs\rhinoremote\lib\site-packages\eppy\modeleditor.py", line 947, in save
with open(filename, "wb") as idf_out:
PermissionError: [Errno 13] Permission denied: 'in.idf'

@jamiebull1  any idea on how to solve this problem?

Thank you in advance for your availability.

**Comment by santoshphilip** [comment]
I can see what is happening.
I am not seeing **_why_** yet

EnergyPlus always does the simulation on a file called `in.idf`
So eppy saves your file as `in.idf` in the working directory (or wherever the script is running)

Somehow eppy does not have permission to write `in.idf` in that location.
You are working in multiple environments (condo, Rhino, mkl-service). one of them is not getting this permission. 
Rhino runs ironpython. Ironpython cannot run C-based modules like numpy without some help.
OK. I am at the edge of my knowledge on this :-( 

`idf.run()` is where it is breaking
Looks like `idf.run()` is being called from Rhino
And it is not working from Rhino

Maybe `idf.run()` does not run from Rhino. (I have never tested this)
Can you confirm this with a simple script - so we can isolate the problem

- another comment
- to report your error in a `fixed width format`
- put a blank line at the start
- leave 4 spaces before each line of the error message
- it will make it easier to read
- error will show up as 

errors:

    File "C:\GH_CPython\PythonFileWritten_1.py", line 27, in
    idf.run(readvars=True, expandobjects=True,output_directory=os.path.join(folderpath,"Output"))
    File "C:\Users\Pc\anaconda3\lib\site-packages\eppy\modeleditor.py", line 1009, in run
    self.saveas("in.idf")
    File "C:\Users\Pc\anaconda3\lib\site-packages\eppy\modeleditor.py", line 974, in saveas
    self.save(filename, lineendings, encoding)
    File "C:\Users\Pc\anaconda3\lib\site-packages\eppy\modeleditor.py", line 947, in save
    with open(filename, "wb") as idf_out:
    PermissionError: [Errno 13] Permission denied: 'in.idf'

**Comment by santoshphilip** [comment]
I sent my response before I saw your reply. Ha!

**Comment by santoshphilip** [comment]
can you do a test purely in Rhino (without condo, numpy mkl-service)
test `idf.run()` with a sample file

**Comment by fracarl** [comment]
Thank you for your reply and sorry for my mistakes but it is my first time on github! And it is also the first time that I work in Python etc. therefore I am still a bit stranger to these environments. 

I wrote the code in spyder because it is the easiest way I found to use Eppy and then I decided to move it in Grasshopper for this reason I am using also conda (probably I am wrong but it is the only way I found). Therefore I don't know how to run eppy without conda as I don't know how to install eppy outside this environment. 

I have simplified as much as possible the code leaving only the path load and idf.run. If you have any suggestions to solve this issue and run it without conda I will be glad to try it! At the moment the simplified code that I run is 

    from eppy import modeleditor
    from eppy.modeleditor import IDF
    folderpath = r'C:\Users\Pc\Documents\Dottorato\...\Prova Python'
    iddfile = r'C:\Users\Pc\Documents\Dottorato\...\Prova Python\V9-3-0-Energy+.idd'
    idfname = r'C:\Users\Pc\Documents\Dottorato\...\SimpleGlaz_SmallOff_Brindisi.idf'
    epwfile = r'C:\Users\Pc\Documents\Dottorato\...\ITA_Brindisi.163200_IWEC.epw'
    IDF.setiddname(iddfile)
    idf = IDF(idfname, epwfile)
    idf.run()

Using the conda path(C:\Users\Pc\anaconda3\envs\rhinoremote\python.exe) for locating Python the errors are:   

    Traceback (most recent call last):
    File "C:\GH_CPython\PythonFileWritten_4.py", line 42, in <module>
    idf.run()
    File "C:\Users\Pc\anaconda3\envs\rhinoremote\lib\site-packages\eppy\modeleditor.py", line 1009, in run
    self.saveas("in.idf")
    File "C:\Users\Pc\anaconda3\envs\rhinoremote\lib\site-packages\eppy\modeleditor.py", line 974, in saveas
    self.save(filename, lineendings, encoding)
    File "C:\Users\Pc\anaconda3\envs\rhinoremote\lib\site-packages\eppy\modeleditor.py", line 947, in save
    with open(filename, "wb") as idf_out:
    PermissionError: [Errno 13] Permission denied: 'in.idf'

While using the direct Path for locating Python (C:\Users\Pc\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Python 3.8) the errors are:

    Traceback (most recent call last):
    File "C:\GH_CPython\PythonFileWritten_1.py", line 8, in <module>
    from eppy import modeleditor
    ModuleNotFoundError: No module named 'eppy'

**Comment by Udaragithub** [comment]
Hi @fracarl ,
Were you able to find a solution for this? 
I am also getting the same error when I try to run Eplus from Dynamo :( .

**Comment by matteomerli** [comment]
Hi @santoshphilip @Udaragithub @fracarl ,
I'm having almost the same error using eppy from GH_CPython.

**Comment by santoshphilip** [comment]
@Udaragithub , What is Dynamo
If I have the environment, I can take a stab at the problem again.

**Comment by VaanHUANG** [comment]
@santoshphilip Hi I have a similar problem and I am not sure if I should open a new issue.

I try to import Eppy in a Grasshopper component using Python and it simply cannot detect the library Eppy:

```python
import sys
pathnameto_eppy = 'c:/users/hchuanshan/appdata/roaming/python/python39/site-packages/eppy'
sys.path.append(pathnameto_eppy)
from eppy import modeleditor
from eppy.modeleditor import IDF
```

The error it gives simply says "invalid syntax". I suppose I should put Eppy in the right directory? But I don't know where I should put it. Or is it because that Eppy cannot be used inside Grasshopper component?

For your information, I install Eppy through pip, and I run Grasshopper with Rhino 7 on Windows 11. The IronPython version is 2.7. 

If you have any thoughts on this, I would love to hear from you. Thank you in advance! 

Best Regards

**Comment by santoshphilip** [comment]
@VaanHUANG 

the latest version of eppy runs only in python3 (it was getting hard to maintain the python2 version)
Can you look thru the older versions of eppy and find a version that works with python2.

I think the older version should work in Grasshopper.
If you run into issues, open a new issue and I'll take a look

**Comment by VaanHUANG** [comment]
@santoshphilip Thank you for your advice!

I will try rolling back to an older version first. If it does not work, I will open a new issue with all necessary information.
