### ISSUE TITLE
Multiple Processing with eppy gives error

### ISSUE THREAD

**Issue by orcunkoraliseri** [santoshphilip/eppy#319]
I have tried multiple processing with eppy from the link below, _Running in parallel processes using Generators._ 
But I confronted with _EnergyPlusRunError_.  Is there any solution about it? Thank you.
- https://eppy.readthedocs.io/en/latest/runningeplus.html
_runIDFs_ generates _idfs_ but can not start simulations. Therefore, there is not any _.err_ file. 

The system cannot find the path specified.
The system cannot find the path specified.
multiprocessing.pool.RemoteTraceback: `

Traceback (most recent call last):
  File "D:\UBEM\Software\anaconda3\envs\ubem\lib\site-packages\eppy\runner\run_functions.py", line 356, in run
    check_call(cmd)
  File "D:\UBEM\Software\anaconda3\envs\ubem\lib\subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:/EnergyPlusV8-9-0\\energyplus.exe', '--weather', 'D:\\ATI\\WeatherData\\TUR_AN_Esenboga.171280_TMYx.2004-2018.epw', '--output-directory', 'D:\\ATI\\Code', '--expandobjects', '--readvars', '--output-prefix', 'Ankara_Residential', 'D:\\ATI\\Code\\multi_runs\\idf_1\\in.idf']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\UBEM\Software\anaconda3\envs\ubem\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "D:\UBEM\Software\anaconda3\envs\ubem\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "D:\UBEM\Software\anaconda3\envs\ubem\lib\site-packages\eppy\runner\run_functions.py", line 204, in multirunner
    run(*args[0], **args[1])
  File "D:\UBEM\Software\anaconda3\envs\ubem\lib\site-packages\eppy\runner\run_functions.py", line 361, in run
    raise EnergyPlusRunError(message)
eppy.runner.run_functions.EnergyPlusRunError: 

Contents of EnergyPlus error file at D:\ATI\Code\eplusout.err
<File not found>

**Comment by santoshphilip** [comment]
first look, I am not seeing where the problem is coming from. 
I need to dig a little deeper.

**Comment by jamiebull1** [comment]
Have you tried running from the command line?

`C:/EnergyPlusV8-9-0\energyplus.exe --weather D:\ATI\WeatherData\TUR_AN_Esenboga.171280_TMYx.2004-2018.epw --output-directory D:\ATI\Code --expandobjects --readvars --output-prefix Ankara_Residential D:\ATI\Code\multi_runs\idf_1\in.idf`

**Comment by santoshphilip** [comment]
Can you post your code snippet that triggered the error

**Comment by orcunkoraliseri** [comment]
Thank you for your quick answer.

Actually, it is the same code that you shared on the documentation, under the _Running in parallel processes using Generators_ part. I just changed the `idd` (as E+ 8-9-0), `idf`, `epw`. I searched for the problem first on the web, then I found a solution. It proposes to change `Popen (shell=True)` in `subprocess` at `runIDFs` function. Then, I confronted with the `eppy.runner.run_functions.EnergyPlusRunError` as I mentioned above. 

These are the `idf`,  `epw` files and the `.py`:
- https://drive.google.com/drive/u/3/folders/10xt9YcnUXycXW5fzZlozb6OqhpeRRQQH

I did not try with the command line. If I can handle this multiple processing file, I will simulate more than 1000 simulations. I am using Pycharm.

If I do not change the `Popen (shell=False)` in `subprocess` at `runIDFs` function, I confront with another error.

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "D:\UBEM\Software\anaconda3\envs\ubem\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "D:\UBEM\Software\anaconda3\envs\ubem\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "D:\UBEM\Software\anaconda3\envs\ubem\lib\site-packages\eppy\runner\run_functions.py", line 204, in multirunner
    run(*args[0], **args[1])
  File "D:\UBEM\Software\anaconda3\envs\ubem\lib\site-packages\eppy\runner\run_functions.py", line 356, in run
    check_call(cmd)
  File "D:\UBEM\Software\anaconda3\envs\ubem\lib\subprocess.py", line 358, in check_call
    retcode = call(*popenargs, **kwargs)
  File "D:\UBEM\Software\anaconda3\envs\ubem\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "D:\UBEM\Software\anaconda3\envs\ubem\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "D:\UBEM\Software\anaconda3\envs\ubem\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:/ATI/Code/TrialMultipleProcessing.py", line 40, in <module>
    main()
  File "D:/ATI/Code/TrialMultipleProcessing.py", line 37, in main
    runIDFs(runs, num_CPUs)
  File "D:\UBEM\Software\anaconda3\envs\ubem\lib\site-packages\eppy\runner\run_functions.py", line 170, in runIDFs
    pool.map(multirunner, prepared_runs)
  File "D:\UBEM\Software\anaconda3\envs\ubem\lib\multiprocessing\pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "D:\UBEM\Software\anaconda3\envs\ubem\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by santoshphilip** [comment]
as @jamiebull1 mentioned in a previous comment - can you try the command line in his comment.
Trying to isolate where the problem is coming from.

**Comment by orcunkoraliseri** [comment]
I tried on Anaconda prompt. The function can not locate the `idf `file 

```
Traceback (most recent call last):
  File "TrialMultipleProcessing.py", line 40, in <module>
    main()
  File "TrialMultipleProcessing.py", line 37, in main
    runIDFs(runs, num_CPUs)
  File "D:\UBEM\Software\anaconda3\envs\UBEM\lib\site-packages\eppy\runner\run_functions.py", line 170, in runIDFs
    pool.map(multirunner, prepared_runs)
  File "D:\UBEM\Software\anaconda3\envs\UBEM\lib\multiprocessing\pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "D:\UBEM\Software\anaconda3\envs\UBEM\lib\multiprocessing\pool.py", line 383, in _map_async
    iterable = list(iterable)
  File "D:\UBEM\Software\anaconda3\envs\UBEM\lib\site-packages\eppy\runner\run_functions.py", line 166, in <genexpr>
    prepare_run(run_id, run_data) for run_id, run_data in enumerate(jobs)
  File "TrialMultipleProcessing.py", line 33, in <genexpr>
    runs = ((idf, make_eplaunch_options(idf) ) for idf in idfs)
  File "TrialMultipleProcessing.py", line 32, in <genexpr>
    idfs = (IDF(fname, epwfile) for fname in fnames)
  File "D:\UBEM\Software\anaconda3\envs\UBEM\lib\site-packages\eppy\modeleditor.py", line 548, in __init__
    self.read()
  File "D:\UBEM\Software\anaconda3\envs\UBEM\lib\site-packages\eppy\modeleditor.py", line 673, in read
    self.idfname, self.iddname, self, commdct=self.idd_info, block=self.block
  File "D:\UBEM\Software\anaconda3\envs\UBEM\lib\site-packages\eppy\idfreader.py", line 294, in idfreader1
    fname, iddfile=iddfile, commdct=commdct, block=block
  File "D:\UBEM\Software\anaconda3\envs\UBEM\lib\site-packages\eppy\EPlusInterfaceFunctions\readidf.py", line 93, in readdatacommdct1
    data = eplusdata.Eplusdata(theidd, idfname)
  File "D:\UBEM\Software\anaconda3\envs\UBEM\lib\site-packages\eppy\EPlusInterfaceFunctions\eplusdata.py", line 105, in __init__
    fnamefobject = open(fname, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'Ankara_Residential.idf'
```

**Comment by santoshphilip** [comment]
I assume the anaconda prompt is a python prompt. (Not familiar with anaconda)
I am seeing python in your error message above.

Can you open a `CMD` window.  (You are not using python this)
you can find the `CMD` by using the search button on the left corner of your Windows machine
https://www.lifewire.com/how-to-open-command-prompt-2618089

and run 

    C:/EnergyPlusV8-9-0\energyplus.exe --weather D:\ATI\WeatherData\TUR_AN_Esenboga.171280_TMYx.2004-2018.epw --output-directory D:\ATI\Code --expandobjects --readvars --output-prefix Ankara_Residential D:\ATI\Code\multi_runs\idf_1\in.idf

We want to make sure that the command line works. 
eppy uses the command line internally

**Comment by orcunkoraliseri** [comment]
Thank you for your concern. I tested on `command line` then the same problem happened. I found the problem with this issue. 
- https://github.com/santoshphilip/eppy/issues/237
The problem was the directory of `Energyplus`. You mentioned before but I did not realize in the first place @jamiebull1.
 I installed E+ on `C:/EnergyPlusV8-9-0`. The `runIDFs` function can see the `E+`.

**Comment by santoshphilip** [comment]
@orcunkoraliseri , your last comment was not clear.
Did you fix the problem ?
How did you do it.
OR
There is still a problem
- E+ not not running from command line (no eppy or python involved)
- idf.run() not running (problem is in eppy)

Can you clarify.

I may want to update eppy to give clearer error messages.
I am getting a lot issues opened on idf.run()  :-(

**Comment by orcunkoraliseri** [comment]
Thank you for asking. I solved the problem with `runIDFs`. The problem was the location of the EnergyPlus. It should be in the` C:` directory. My Energyplus was in `D:`. That is why `runIDFs` can not see the .`idd` file. Then, I installed the EnergyPlus in `C:` and the problem is solved. I guess you can close this issue. Thank you for your help.
