### ISSUE TITLE
Issue in printidf function

### ISSUE THREAD

**Issue by revathij** [santoshphilip/eppy#332]
Hi Santosh,

I have tried to install the eppy with the energy plus version of 9.3 and tried to run the below code.

from eppy.modeleditor import IDF
from eppy import hvacbuilder

from io import StringIO
iddfile = "/usr/local/EnergyPlus-9-3-0/Energy+.idd"
IDF.setiddname(iddfile)

fname1 = "/usr/local/EnergyPlus-9-3-0/ExampleFiles/UnitHeaterGasElec.idf"
idf1 = IDF(fname1)
idf1.printidf()

idf = IDF(StringIO('')) # makes an empty idf file in memory with no file name
loopname = "p_loop"
sloop = ['sb0', ['sb1', 'sb2', 'sb3'], 'sb4'] # supply side of the loop
dloop = ['db0', ['db1', 'db2', 'db3'], 'db4'] # demand side of the loop
hvacbuilder.makeplantloop(idf, loopname, sloop, dloop)
idf.saveas("test.idf")

However, I am getting the below error. Could you please help on this. 

Using python version 3.6 and installed eppy "pip install eppy"

(ecocc) ecocc@thales:~/eppy$ python testeppy.py 
Traceback (most recent call last):
  File "testeppy.py", line 9, in <module>
    idf1 = IDF(fname1)
  File "/home/ecocc/anaconda3/envs/ecocc/lib/python3.6/site-packages/eppy/modeleditor.py", line 548, in __init__
    self.read()
  File "/home/ecocc/anaconda3/envs/ecocc/lib/python3.6/site-packages/eppy/modeleditor.py", line 673, in read
    self.idfname, self.iddname, self, commdct=self.idd_info, block=self.block
  File "/home/ecocc/anaconda3/envs/ecocc/lib/python3.6/site-packages/eppy/idfreader.py", line 294, in idfreader1
    fname, iddfile=iddfile, commdct=commdct, block=block
  File "/home/ecocc/anaconda3/envs/ecocc/lib/python3.6/site-packages/eppy/EPlusInterfaceFunctions/readidf.py", line 88, in readdatacommdct1
    block, commlst, commdct, idd_index = parse_idd.extractidddata(iddfile)
  File "/home/ecocc/anaconda3/envs/ecocc/lib/python3.6/site-packages/decorator.py", line 231, in fun
    return caller(func, *(extras + args), **kw)
TypeError: make_idd_index() missing 1 required positional argument: 'debug'

**Comment by santoshphilip** [comment]
@revathij ,

Sorry about that. It is broken
`hvacbuilder.makeplantloop` and  `loopdiagram.py` are broken since after E+ 8.4

`hvacbuilder.makeplantloop` is low priority for being fixed.
`loopdiagram.py` is likely to be fixed soon.

I probably need to explain why it broken.
 `<start rant>`
The details of who E+ are built is badly documented. (to be honest, it is undocumented). One has to open up the example files and do a lot of detective work to tease out what is going on. This included reading the IDF text files and tracing the diagrams by hand to figure it out. Anytime something changes between versions, everything breaks in `hvacbuilder.makeplantloop` and `loopdiagram.py`.
`<end rant>` :-(
fortunately these changes are rare. I should probably fix the loops.
I must say everything else in E+ is superbly documented. The IDD is self documenting. It is so well documented that `eppy` works seamlessly between all versions of E+ (except the loop stuff)

**Comment by santoshphilip** [comment]
I am withdrawing my `rant` in the previous comment.
I found the document "PlantApplicationGuide.pdf" in the E+ documentation. This may give me enough clarity on the Plant loops. (I believe the air loops are a little different)

There is a good chance we may get to a fix for this.
It may take some time.

**Comment by nevr1106** [comment]
This might have something to do with EnergyPlus installation itself.

I have been using E+ 9.3.0 for two years. Everything works well with eppy. However, I have to install a 9.3.0 version last month on a new machine, which was downloaded from Github. That's when I start to have this issue. 

When I switch back to the E+ installed two years ago, this error will disappear.

**Comment by santoshphilip** [comment]
Is the issue with `printidf()` only ?
Does it happen if you just read a file and then try to print it ?

**Comment by nevr1106** [comment]
Nope. In my case, it is triggered by eppy.modeleditor.IDF( ).

**Comment by santoshphilip** [comment]
So this is happening with the same version of E+ ie. version 9.3.0
Different time of download

What platform are on (operating system) ?

If I can't recreate the problem, I may need your help in testing.

**Comment by nevr1106** [comment]
@santoshphilip @revathij 

Sorry, I just realized that the installation of E+ has nothing to do with eppy. As long as there is a Energy+.idd file, eppy should work just fine.

The problem is with the new version of **decorator** module. It seems there are some major changes from 4.x.x to 5.x.x for the decorator package. 

After I downgrade decorator from **5.0.6** to **4.4.2**, this error disappears and my script works as designed.

**Comment by santoshphilip** [comment]
thanks ... good job finding that error.
I can take steps from here.

**Comment by santoshphilip** [comment]
@nevr1106 , Would you like to make a pull request and fix this problem 
In requirements.txt make this change

    decorator
    # becomes
    decorator==4.4.2

I could make the change too, but why don't you do so.

**Comment by revathij** [comment]
@santoshphilip , @nevr1106 

Thanks for the reply. 
I have uninstalled and installed the decorator. However I am getting different error.


from eppy.modeleditor import IDF
from eppy import hvacbuilder

from io import StringIO
iddfile = "C:/EnergyPlusV9-3-0/Energy+.idd"
IDF.setiddname(iddfile)


# make the topology of the loop
idf = IDF(StringIO('')) # makes an empty idf file in memory with no file name
loopname = "p_loop"
sloop = ['sb0', ['sb1', 'sb2', 'sb3'], 'sb4'] # supply side of the loop
dloop = ['db0', ['db1', 'db2', 'db3'], 'db4'] # demand side of the loop
hvacbuilder.makeplantloop(idf, loopname, sloop, dloop)
idf.saveas("hhh1.idf")

Error:
(eppy) D:\Thales\ECOCC>python ecocc_HVAC.py
Traceback (most recent call last):
  File "ecocc_HVAC.py", line 28, in <module>
    hvacbuilder.makeplantloop(idf, loopname, sloop, dloop)
  File "C:\Users\revat\Anaconda3\envs\eppy\lib\site-packages\eppy\hvacbuilder.py", line 681, in makeplantloop
    branch = makepipebranch(idf, bname)
  File "C:\Users\revat\Anaconda3\envs\eppy\lib\site-packages\eppy\hvacbuilder.py", line 109, in makepipebranch
    abranch.Component_1_Branch_Control_Type = "Bypass"
  File "C:\Users\revat\Anaconda3\envs\eppy\lib\site-packages\eppy\bunch_subclass.py", line 298, in __setattr__
    raise BadEPFieldError(astr)  # TODO: could raise AttributeError
eppy.bunch_subclass.BadEPFieldError: unable to find field Component_1_Branch_Control_Type

**Comment by santoshphilip** [comment]
@revathij that entire module (hvacbuilder) is broken for the newer versions of E+ (greater than 8.4 i think). I am looking into how to fix it in a robust way. I want to make sure that it doesn't break every time a new version of E+ is released.

So for the near future anything you do with hvacbuilder or loopdiagram will not work :-(
Everything else will work

**Comment by revathij** [comment]
@santoshphilip ,

Thanks a lot

**Comment by santoshphilip** [comment]
@nevr1106 , I made a [comment](https://github.com/santoshphilip/eppy/pull/336#issuecomment-851582488l) at your pull request #336 
Can you take a look and respond when you get a chance
