### ISSUE TITLE
Error when generating diagrams of HVAC loops

### ISSUE THREAD

**Issue by JamesCheng21** [santoshphilip/eppy#425]
Hi! I was testing this function using one of the [DOE small office prototype models](https://www.energycodes.gov/sites/default/files/2022-12/IECC_OfficeSmall_STD2018.zip) when running into this error. Tried a few different models and got different errors. Not sure if this is useful for more robust function

```
(base) C:\Users\Downloads\IECC_OfficeSmall_STD2018>python loopdiagram.py "C:\EnergyPlusV9-0-1\Energy+.idd" IECC_OfficeSmall_STD2018_Atlanta.idf
Couldn't import dot_parser, loading of dot files will not be possible.
constructing the loops
Traceback (most recent call last):
  File "loopdiagram.py", line 569, in <module>
    sys.exit(main())
  File "loopdiagram.py", line 565, in main
    make_and_save_diagram(args.file, args.idd)
  File "loopdiagram.py", line 521, in make_and_save_diagram
    g = process_idf(fname, iddfile)
  File "loopdiagram.py", line 528, in process_idf
    edges = makeairplantloop(data, commdct)
  File "loopdiagram.py", line 361, in makeairplantloop
    equipconnections = loops.extractfields(data, commdct, objkey, fieldlists)
  File "C:\Users\zsc12\Anaconda3\lib\site-packages\eppy\loops.py", line 46, in extractfields
    fieldindex.append(objfields.index(item) + 0)
ValueError: 'Zone Return Air Node Name' is not in list
```

**Comment by santoshphilip** [comment]
@JamesCheng21 , Sorry for the late response.
The diagrams are broken for the new versions of E+. (I wrote them for version 7.6)
I have not had the time to update the.

I am hoping that someone volunteers to do it :-)
